my_string = input("Введите текст: ")
print("Количество символов равно: ", len(my_string))
print("Форматирование текста в верхний регистр:", my_string .upper())
print("Форматирование текста в нижний регистр:", my_string .lower())
print("Удаление пробелов в тексте:", my_string .replace(" ", ""))
print("Вывод первого символа:", my_string[0])
print("Вывод последнего символа:", my_string[-1])
